<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.ricardodlm.springai.mcp.common</groupId>
        <artifactId>common-architecture-fwk</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>common-jwt</artifactId>
    <version>${common-jwt.version}</version>
    <packaging>jar</packaging>
    <name>Commons Implementacion JWT </name>
    <description>
        JWT del cliente MCP propagado
    </description>


    <dependencies>
        <!-- ================================================ -->
        <!-- Spring Security — GrantedAuthority (Authority)   -->
        <!-- Solo el contrato, sin autoconfiguración          -->
        <!-- ================================================ -->
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-core</artifactId>
        </dependency>

    </dependencies>

</project>