<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.ricardodlm.springai.mcp</groupId>
        <artifactId>mcp-architecture-framework</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <groupId>io.github.ricardodlm.springai.mcp.transport</groupId>
    <artifactId>transport-architecture-fwk</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>transport-session-service</module>
        <module>transport-streamable-mvc</module>
        <module>transport-auth-service</module>
        <module>transport-cors-service</module>
    </modules>

</project>